import type {ImageSourcePropType} from 'react-native';

export const images = {
  splashBackground: require('./splash-background.png') as ImageSourcePropType,
  onboardingFind: require('./onboarding-find-green-places.png') as ImageSourcePropType,
  onboardingRoutes: require('./onboarding-follow-nature-routes.png') as ImageSourcePropType,
  onboardingAtlas: require('./onboarding-save-green-atlas.png') as ImageSourcePropType,
  hydeParkLawns: require('./place-hyde-park-lawns.png') as ImageSourcePropType,
  primroseHill: require('./place-primrose-hill.png') as ImageSourcePropType,
  hampsteadHeathMeadows: require('./place-hampstead-heath-meadows.png') as ImageSourcePropType,
  richmondParkGrasslands: require('./place-richmond-park-grasslands.png') as ImageSourcePropType,
  chelseaPhysicGarden: require('./place-chelsea-physic-garden.png') as ImageSourcePropType,
  kewGardensPalmHouse: require('./place-kew-gardens-palm-house.png') as ImageSourcePropType,
  kyotoGarden: require('./place-kyoto-garden.png') as ImageSourcePropType,
  queenMarysGardens: require('./place-queen-marys-gardens.png') as ImageSourcePropType,
  hollandParkQuietWalks: require('./place-holland-park-quiet-walks.png') as ImageSourcePropType,
  stJamesPark: require('./place-st-james-park.png') as ImageSourcePropType,
  greenPark: require('./place-green-park.png') as ImageSourcePropType,
  victoriaEmbankmentGardens: require('./place-victoria-embankment-gardens.png') as ImageSourcePropType,
  regentsCanalGreens: require('./place-regents-canal-greens.png') as ImageSourcePropType,
  thamesPathGreenSections: require('./place-thames-path-green-sections.png') as ImageSourcePropType,
  batterseaParkRiversideLawns: require('./place-battersea-park-riverside-lawns.png') as ImageSourcePropType,
  walthamstowWetlandsGreenPaths: require('./place-walthamstow-wetlands-green-paths.png') as ImageSourcePropType,
  noteGreenRoute: require('./note-how-to-choose-green-route.png') as ImageSourcePropType,
  notePhotography: require('./note-best-time-park-photography.png') as ImageSourcePropType,
  noteBotanical: require('./note-botanical-gardens-slow-travel.png') as ImageSourcePropType,
  noteRiverside: require('./note-riverside-greens-calm-movement.png') as ImageSourcePropType,
  notePicnic: require('./note-picnic-friendly-places.png') as ImageSourcePropType,
  noteReadingPark: require('./note-reading-a-park.png') as ImageSourcePropType,
  noteUrbanNature: require('./note-urban-nature-city.png') as ImageSourcePropType,
  noteAtlas: require('./note-personal-green-atlas.png') as ImageSourcePropType,
  noteLawns: require('./note-open-lawns-relaxing.png') as ImageSourcePropType,
  noteNatureDay: require('./note-plan-calm-nature-day.png') as ImageSourcePropType,
};
